[server]
headless = true
enableCORS = false
port = 8501

[theme]
primaryColor = "#4CAF50"
backgroundColor = "#F0F2F6"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#262730"
font = "sans serif"

[client]
showSidebarNavigation = true
toolbarMode = "minimal"

[logger]
level = "info"

